# Generated by Django 3.1.4 on 2020-12-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyists_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcategory',
            name='user_id',
        ),
    ]
