# Generated by Django 3.1.4 on 2020-12-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyists_app', '0003_auto_20201227_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumdiscussion',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listevent',
            name='num_comment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listevent',
            name='num_hadir',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listforum',
            name='num_comment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listforum',
            name='num_like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
