# Generated by Django 3.1.4 on 2021-03-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyists_app', '0006_auto_20201227_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='listforum',
            name='user_like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
