# Generated by Django 3.1.4 on 2021-03-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyists_app', '0008_listevent_hadir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listevent',
            name='hadir',
            field=models.CharField(blank=True, default='[]', max_length=200, null=True),
        ),
    ]
